version: "3"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
      - logs
    networks:
      - webnet
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432
    volumes:
      - /var/lib/postgresql/data
    networks:
      - webnet
  logs:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - /bitnami/redis/data
    networks:
      - webnet
networks:
  webnet: