version: "3"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database
      - logs
    links:
     - database
     - logs
    networks:
      - webnet
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./static/create-tables.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - webnet
  logs:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6380:6379
    volumes:
      - ./data/redis:/bitnami/redis/data
    networks:
      - webnet
networks:
  webnet: